runtime: python37

env_variables:
  GCP_PROJECT: "book-recsys-253611"
  GCS_BUCKET: "dataset-book"
  FIREBASE_CONFIG: "firebase_config.json"

handlers:
  - url: /static
    static_dir: static
  
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301